name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install ruff mypy pytest pytest-cov
      - run: ruff .
      - run: mypy app
      - run: pytest --cov=app
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
      - name: Login ACR
        run: echo "skip"
      - name: Push image
        run: echo "skip"
      - name: Deploy
        run: echo "skip"
