name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run tests
        run: uv run pytest

